"""
Claude-powered digest summarizer.
Takes a list of Items and returns (html, text) versions of the daily digest.
"""
import os
from datetime import datetime
from typing import List, Tuple

from openai import OpenAI

from sources import Item


OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
MODEL = "google/gemma-3-27b-it:free"


SYSTEM_PROMPT = """You are an expert AI researcher writing a daily briefing for a busy \
engineer who builds with AI agents. Your job: read today's items and produce a tight, \
skimmable TLDR focused on agentic AI, LLM tooling, agent frameworks, and notable model releases.

Rules:
- Lead with the 3-5 most important items. Everything else is secondary.
- Group by theme (e.g. "Model releases", "Agent frameworks", "Research", "Industry").
- One sentence per item. Be direct. No hype words ("revolutionary", "game-changing").
- Include the source link inline as markdown: [Source name](url)
- Skip duplicates and low-signal items silently.
- If nothing meaningful happened in a category, omit it entirely.
- End with a one-line "Why it matters" takeaway for the day.

Output format: clean markdown. Use ## for section headers, - for bullets. No preamble, no closing."""


def _format_items_for_prompt(items: List[Item]) -> str:
    lines = []
    for i, item in enumerate(items, 1):
        lines.append(
            f"[{i}] Source: {item.source}\n"
            f"    Title: {item.title}\n"
            f"    URL: {item.url}\n"
            f"    Published: {item.published.strftime('%Y-%m-%d %H:%M UTC')}\n"
            f"    Excerpt: {item.summary}\n"
        )
    return "\n".join(lines)


def _markdown_to_html(md: str) -> str:
    """Minimal markdown -> HTML for email. Handles headers, bullets, links, bold."""
    import re

    html_lines = []
    in_list = False
    for line in md.split("\n"):
        stripped = line.strip()

        # Headers
        if stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2 style='color:#1a1a1a;margin-top:24px'>{stripped[3:]}</h2>")
            continue
        if stripped.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h1 style='color:#1a1a1a'>{stripped[2:]}</h1>")
            continue

        # Bullets
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append("<ul style='padding-left:20px'>")
                in_list = True
            html_lines.append(f"<li style='margin-bottom:8px'>{stripped[2:]}</li>")
            continue

        # Blank line closes list
        if not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            continue

        if in_list:
            html_lines.append("</ul>")
            in_list = False
        html_lines.append(f"<p>{stripped}</p>")

    if in_list:
        html_lines.append("</ul>")

    html = "\n".join(html_lines)
    # Links [text](url)
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)",
                  r"<a href='\2' style='color:#0066cc'>\1</a>", html)
    # Bold **text**
    html = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", html)
    # Italic *text*
    html = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", html)

    today = datetime.now().strftime("%A, %B %d, %Y")
    return f"""<!DOCTYPE html>
<html>
<body style="font-family:-apple-system,system-ui,sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#222;line-height:1.5">
  <div style="border-bottom:2px solid #eee;padding-bottom:12px;margin-bottom:20px">
    <h1 style="margin:0;font-size:22px">🤖 AI Agents Daily</h1>
    <p style="margin:4px 0 0;color:#888;font-size:13px">{today}</p>
  </div>
  {html}
  <hr style="margin-top:32px;border:none;border-top:1px solid #eee">
  <p style="color:#999;font-size:12px">Generated by your personal digest bot. Sources pulled from curated RSS feeds.</p>
  <p style="color:#999;font-size:12px">You're receiving this because you subscribed to AI Agents Daily. <a href="{{unsubscribe_url}}" style="color:#999">Unsubscribe</a>.</p>
</body>
</html>"""


def summarize_digest(items: List[Item]) -> Tuple[str, str]:
    """Returns (html_body, text_body)."""
    client = OpenAI(
        base_url=OPENROUTER_BASE_URL,
        api_key=os.environ["OPENROUTER_API_KEY"],
    )

    formatted = _format_items_for_prompt(items)
    user_msg = f"Today's items ({len(items)} total):\n\n{formatted}\n\nWrite the briefing."

    resp = client.chat.completions.create(
        model=MODEL,
        max_tokens=2000,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
    )
    markdown = (resp.choices[0].message.content or "").strip()
    text_with_footer = markdown + "\n\n---\nUnsubscribe: {{unsubscribe_url}}\n"
    return _markdown_to_html(markdown), text_with_footer
